### ISSUE TITLE
Receiving multiple SMS at once

### ISSUE THREAD

**Issue by nandra** [warthog618/sms#8]
Hi,

thanks for great library. I'm using it for receiving sms. My usecase if I can receive at same time like 70 sms at once. Does library will handle it asynchronously (have some internal buffer or how it is done please)? Also do I need to delete received SMS (I juts know if from older phones that they refuse to receive is some number of SMS is received). Thanks.

**Comment by warthog618** [comment]
I'm could swear I replied to this already, but apparently not...
This library is purely about encoding and decoding SMS PDUs.  It does not interact with the modem that sends or receives the PDUs - that is outside the scope of this library.
The issue with "older phones" you mention is probably related to a setup where the modem is configured to store received SMS PDUs to the SIM card rather than passing them directly to the application, and the application then needs to retrieve them from the SIM.  Again that is outside the scope of this library.
